// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Participant is the predicate function for participant builders.
type Participant func(*sql.Selector)

// TitleImage is the predicate function for titleimage builders.
type TitleImage func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
