# Configuration can be overwritten by environment variables.
# Use uppercase values delimited by _ and prefixed with KUEFA.
# e.g. KUEFA_POSTGRES_HOST

debug: false

postgres:
  host: localhost
  port: 5432
  user: kuefa
  password: kuefa
  database: kuefa
  options:
    - sslmode=disable

auth:
  provider: local
  session:
    name: kuefa
    lifetime: 720h
    secret: my-secret-value

web:
  root: frontend/dist
  port: 3001
  storage: store/public
