// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fredi12345/kuefa-karben/src/ent/titleimage"
	"github.com/google/uuid"
)

// TitleImageCreate is the builder for creating a TitleImage entity.
type TitleImageCreate struct {
	config
	mutation *TitleImageMutation
	hooks    []Hook
}

// SetCreated sets the "created" field.
func (tic *TitleImageCreate) SetCreated(t time.Time) *TitleImageCreate {
	tic.mutation.SetCreated(t)
	return tic
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (tic *TitleImageCreate) SetNillableCreated(t *time.Time) *TitleImageCreate {
	if t != nil {
		tic.SetCreated(*t)
	}
	return tic
}

// SetID sets the "id" field.
func (tic *TitleImageCreate) SetID(u uuid.UUID) *TitleImageCreate {
	tic.mutation.SetID(u)
	return tic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tic *TitleImageCreate) SetNillableID(u *uuid.UUID) *TitleImageCreate {
	if u != nil {
		tic.SetID(*u)
	}
	return tic
}

// Mutation returns the TitleImageMutation object of the builder.
func (tic *TitleImageCreate) Mutation() *TitleImageMutation {
	return tic.mutation
}

// Save creates the TitleImage in the database.
func (tic *TitleImageCreate) Save(ctx context.Context) (*TitleImage, error) {
	var (
		err  error
		node *TitleImage
	)
	tic.defaults()
	if len(tic.hooks) == 0 {
		if err = tic.check(); err != nil {
			return nil, err
		}
		node, err = tic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TitleImageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tic.check(); err != nil {
				return nil, err
			}
			tic.mutation = mutation
			if node, err = tic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tic.hooks) - 1; i >= 0; i-- {
			if tic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tic *TitleImageCreate) SaveX(ctx context.Context) *TitleImage {
	v, err := tic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tic *TitleImageCreate) Exec(ctx context.Context) error {
	_, err := tic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tic *TitleImageCreate) ExecX(ctx context.Context) {
	if err := tic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tic *TitleImageCreate) defaults() {
	if _, ok := tic.mutation.Created(); !ok {
		v := titleimage.DefaultCreated()
		tic.mutation.SetCreated(v)
	}
	if _, ok := tic.mutation.ID(); !ok {
		v := titleimage.DefaultID()
		tic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tic *TitleImageCreate) check() error {
	if _, ok := tic.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "TitleImage.created"`)}
	}
	return nil
}

func (tic *TitleImageCreate) sqlSave(ctx context.Context) (*TitleImage, error) {
	_node, _spec := tic.createSpec()
	if err := sqlgraph.CreateNode(ctx, tic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (tic *TitleImageCreate) createSpec() (*TitleImage, *sqlgraph.CreateSpec) {
	var (
		_node = &TitleImage{config: tic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: titleimage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: titleimage.FieldID,
			},
		}
	)
	if id, ok := tic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tic.mutation.Created(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: titleimage.FieldCreated,
		})
		_node.Created = value
	}
	return _node, _spec
}

// TitleImageCreateBulk is the builder for creating many TitleImage entities in bulk.
type TitleImageCreateBulk struct {
	config
	builders []*TitleImageCreate
}

// Save creates the TitleImage entities in the database.
func (ticb *TitleImageCreateBulk) Save(ctx context.Context) ([]*TitleImage, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ticb.builders))
	nodes := make([]*TitleImage, len(ticb.builders))
	mutators := make([]Mutator, len(ticb.builders))
	for i := range ticb.builders {
		func(i int, root context.Context) {
			builder := ticb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TitleImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ticb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ticb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ticb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ticb *TitleImageCreateBulk) SaveX(ctx context.Context) []*TitleImage {
	v, err := ticb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ticb *TitleImageCreateBulk) Exec(ctx context.Context) error {
	_, err := ticb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ticb *TitleImageCreateBulk) ExecX(ctx context.Context) {
	if err := ticb.Exec(ctx); err != nil {
		panic(err)
	}
}
