// Code generated by entc, DO NOT EDIT.

package titleimage

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the titleimage type in the database.
	Label = "title_image"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// Table holds the table name of the titleimage in the database.
	Table = "title_images"
)

// Columns holds all SQL columns for titleimage fields.
var Columns = []string{
	FieldID,
	FieldCreated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
